from view.app import App
from view.register import Register
from view.login import Login
from view.menu import Menu
from view.upload import Upload
from view.preferences import Preferences
from view.popup_window import PopupWindow
from view.about import About
from view.my_files import MyFiles
